services:
    front:
        build: ./front/my-app
        ports:
            - "80:80"
    back:
        environment: 
            - FRONTEND_URL=http://localhost
        build: ./back
        ports:
            - "5000:5000"
        